// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: cache.proto

package cachepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_cache_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_cache_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type SetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = default server TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRequest) Reset() {
	*x = SetRequest{}
	mi := &file_cache_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRequest) ProtoMessage() {}

func (x *SetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRequest.ProtoReflect.Descriptor instead.
func (*SetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{2}
}

func (x *SetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetResponse) Reset() {
	*x = SetResponse{}
	mi := &file_cache_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetResponse) ProtoMessage() {}

func (x *SetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetResponse.ProtoReflect.Descriptor instead.
func (*SetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{3}
}

func (x *SetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_cache_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_cache_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type MGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MGetRequest) Reset() {
	*x = MGetRequest{}
	mi := &file_cache_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetRequest) ProtoMessage() {}

func (x *MGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetRequest.ProtoReflect.Descriptor instead.
func (*MGetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{6}
}

func (x *MGetRequest) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type KeyValueItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValueItem) Reset() {
	*x = KeyValueItem{}
	mi := &file_cache_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValueItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValueItem) ProtoMessage() {}

func (x *KeyValueItem) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValueItem.ProtoReflect.Descriptor instead.
func (*KeyValueItem) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{7}
}

func (x *KeyValueItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValueItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *KeyValueItem) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type MGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*KeyValueItem        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MGetResponse) Reset() {
	*x = MGetResponse{}
	mi := &file_cache_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MGetResponse) ProtoMessage() {}

func (x *MGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MGetResponse.ProtoReflect.Descriptor instead.
func (*MGetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{8}
}

func (x *MGetResponse) GetItems() []*KeyValueItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type SetItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"` // 0 = default server TTL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetItem) Reset() {
	*x = SetItem{}
	mi := &file_cache_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetItem) ProtoMessage() {}

func (x *SetItem) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetItem.ProtoReflect.Descriptor instead.
func (*SetItem) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{9}
}

func (x *SetItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetItem) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SetItem) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type MSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*SetItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSetRequest) Reset() {
	*x = MSetRequest{}
	mi := &file_cache_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSetRequest) ProtoMessage() {}

func (x *MSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSetRequest.ProtoReflect.Descriptor instead.
func (*MSetRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{10}
}

func (x *MSetRequest) GetItems() []*SetItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type MSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MSetResponse) Reset() {
	*x = MSetResponse{}
	mi := &file_cache_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MSetResponse) ProtoMessage() {}

func (x *MSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MSetResponse.ProtoReflect.Descriptor instead.
func (*MSetResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{11}
}

func (x *MSetResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *MSetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_cache_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{12}
}

type StatsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EntryCount       int64                  `protobuf:"varint,1,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	HitCount         int64                  `protobuf:"varint,2,opt,name=hit_count,json=hitCount,proto3" json:"hit_count,omitempty"`
	MissCount        int64                  `protobuf:"varint,3,opt,name=miss_count,json=missCount,proto3" json:"miss_count,omitempty"`
	HitRate          float64                `protobuf:"fixed64,4,opt,name=hit_rate,json=hitRate,proto3" json:"hit_rate,omitempty"`
	EvacuateCount    int64                  `protobuf:"varint,5,opt,name=evacuate_count,json=evacuateCount,proto3" json:"evacuate_count,omitempty"`
	ExpiredCount     int64                  `protobuf:"varint,6,opt,name=expired_count,json=expiredCount,proto3" json:"expired_count,omitempty"`
	MemoryLimitBytes int64                  `protobuf:"varint,7,opt,name=memory_limit_bytes,json=memoryLimitBytes,proto3" json:"memory_limit_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_cache_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cache_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_cache_proto_rawDescGZIP(), []int{13}
}

func (x *StatsResponse) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *StatsResponse) GetHitCount() int64 {
	if x != nil {
		return x.HitCount
	}
	return 0
}

func (x *StatsResponse) GetMissCount() int64 {
	if x != nil {
		return x.MissCount
	}
	return 0
}

func (x *StatsResponse) GetHitRate() float64 {
	if x != nil {
		return x.HitRate
	}
	return 0
}

func (x *StatsResponse) GetEvacuateCount() int64 {
	if x != nil {
		return x.EvacuateCount
	}
	return 0
}

func (x *StatsResponse) GetExpiredCount() int64 {
	if x != nil {
		return x.ExpiredCount
	}
	return 0
}

func (x *StatsResponse) GetMemoryLimitBytes() int64 {
	if x != nil {
		return x.MemoryLimitBytes
	}
	return 0
}

var File_cache_proto protoreflect.FileDescriptor

const file_cache_proto_rawDesc = "" +
	"\n" +
	"\vcache.proto\x12\x05cache\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"U\n" +
	"\n" +
	"SetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"\x1d\n" +
	"\vSetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\" \n" +
	"\x0eDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"!\n" +
	"\vMGetRequest\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"L\n" +
	"\fKeyValueItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"9\n" +
	"\fMGetResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.cache.KeyValueItemR\x05items\"R\n" +
	"\aSetItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x05R\n" +
	"ttlSeconds\"3\n" +
	"\vMSetRequest\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.cache.SetItemR\x05items\"4\n" +
	"\fMSetResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x05R\x05count\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\"\x0e\n" +
	"\fStatsRequest\"\x81\x02\n" +
	"\rStatsResponse\x12\x1f\n" +
	"\ventry_count\x18\x01 \x01(\x03R\n" +
	"entryCount\x12\x1b\n" +
	"\thit_count\x18\x02 \x01(\x03R\bhitCount\x12\x1d\n" +
	"\n" +
	"miss_count\x18\x03 \x01(\x03R\tmissCount\x12\x19\n" +
	"\bhit_rate\x18\x04 \x01(\x01R\ahitRate\x12%\n" +
	"\x0eevacuate_count\x18\x05 \x01(\x03R\revacuateCount\x12#\n" +
	"\rexpired_count\x18\x06 \x01(\x03R\fexpiredCount\x12,\n" +
	"\x12memory_limit_bytes\x18\a \x01(\x03R\x10memoryLimitBytes2\xb3\x02\n" +
	"\x05Cache\x12,\n" +
	"\x03Get\x12\x11.cache.GetRequest\x1a\x12.cache.GetResponse\x12,\n" +
	"\x03Set\x12\x11.cache.SetRequest\x1a\x12.cache.SetResponse\x125\n" +
	"\x06Delete\x12\x14.cache.DeleteRequest\x1a\x15.cache.DeleteResponse\x12/\n" +
	"\x04MGet\x12\x12.cache.MGetRequest\x1a\x13.cache.MGetResponse\x12/\n" +
	"\x04MSet\x12\x12.cache.MSetRequest\x1a\x13.cache.MSetResponse\x125\n" +
	"\bGetStats\x12\x13.cache.StatsRequest\x1a\x14.cache.StatsResponseB\n" +
	"Z\b/cachepbb\x06proto3"

var (
	file_cache_proto_rawDescOnce sync.Once
	file_cache_proto_rawDescData []byte
)

func file_cache_proto_rawDescGZIP() []byte {
	file_cache_proto_rawDescOnce.Do(func() {
		file_cache_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)))
	})
	return file_cache_proto_rawDescData
}

var file_cache_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_cache_proto_goTypes = []any{
	(*GetRequest)(nil),     // 0: cache.GetRequest
	(*GetResponse)(nil),    // 1: cache.GetResponse
	(*SetRequest)(nil),     // 2: cache.SetRequest
	(*SetResponse)(nil),    // 3: cache.SetResponse
	(*DeleteRequest)(nil),  // 4: cache.DeleteRequest
	(*DeleteResponse)(nil), // 5: cache.DeleteResponse
	(*MGetRequest)(nil),    // 6: cache.MGetRequest
	(*KeyValueItem)(nil),   // 7: cache.KeyValueItem
	(*MGetResponse)(nil),   // 8: cache.MGetResponse
	(*SetItem)(nil),        // 9: cache.SetItem
	(*MSetRequest)(nil),    // 10: cache.MSetRequest
	(*MSetResponse)(nil),   // 11: cache.MSetResponse
	(*StatsRequest)(nil),   // 12: cache.StatsRequest
	(*StatsResponse)(nil),  // 13: cache.StatsResponse
}
var file_cache_proto_depIdxs = []int32{
	7,  // 0: cache.MGetResponse.items:type_name -> cache.KeyValueItem
	9,  // 1: cache.MSetRequest.items:type_name -> cache.SetItem
	0,  // 2: cache.Cache.Get:input_type -> cache.GetRequest
	2,  // 3: cache.Cache.Set:input_type -> cache.SetRequest
	4,  // 4: cache.Cache.Delete:input_type -> cache.DeleteRequest
	6,  // 5: cache.Cache.MGet:input_type -> cache.MGetRequest
	10, // 6: cache.Cache.MSet:input_type -> cache.MSetRequest
	12, // 7: cache.Cache.GetStats:input_type -> cache.StatsRequest
	1,  // 8: cache.Cache.Get:output_type -> cache.GetResponse
	3,  // 9: cache.Cache.Set:output_type -> cache.SetResponse
	5,  // 10: cache.Cache.Delete:output_type -> cache.DeleteResponse
	8,  // 11: cache.Cache.MGet:output_type -> cache.MGetResponse
	11, // 12: cache.Cache.MSet:output_type -> cache.MSetResponse
	13, // 13: cache.Cache.GetStats:output_type -> cache.StatsResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_cache_proto_init() }
func file_cache_proto_init() {
	if File_cache_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cache_proto_rawDesc), len(file_cache_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cache_proto_goTypes,
		DependencyIndexes: file_cache_proto_depIdxs,
		MessageInfos:      file_cache_proto_msgTypes,
	}.Build()
	File_cache_proto = out.File
	file_cache_proto_goTypes = nil
	file_cache_proto_depIdxs = nil
}
